### PR TITLE
Add Chinese translation (translator: yc000764)

### PR DESCRIPTION
**Pull request by duduluu**

### CODE REVIEW

**Comment by scuba156** [comment]
Looks good. I just added a single line to the English language which needs translation. Also a LanguageInfo.xml would be nice that gives credit to yc000764, but I can do that myself afterwards.

**Comment by duduluu** [comment]
Where is the added single line to English?
Is readme.txt file fine? The LanguageInfo.xml outside of Core won't be display. Maybe just a simple readme is better.

**Comment by scuba156** [comment]
The added line can be found here https://github.com/scuba156/ModListBackup/commit/98bdc82b7e2a7d7ca8cd52faca90158be1d73144

using a LanguageInfo.xml would be better for future compatibility with RimWorld, but I am more than happy to do that.

**Comment by duduluu** [comment]
OK, i rebase it to follow up the added content, and the LanugageInfo.xml file.

**Comment by scuba156** [comment]
Thank you. Update will be released soon with the included soon. There is also one more string that needs translation https://github.com/scuba156/ModListBackup/commit/e7f78ba56e176c1da3dfa6209a8fd589617199fd sorry

**Pull request merged**
